// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cexfrqawaxpozcfgemrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNleGZycWF3YXhwb3pjZmdlbXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjQ1MzQsImV4cCI6MjA2MjMwMDUzNH0.FWd75irbxi0h-SROv_Mgktv4SmOf7ZizL2tX6K5rYew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);